Haber.Web/Areas/Admin/Controllers/HaberController.cs
using Haber.Model;
using Haber.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Haber.Web.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    [Authorize]
    public class HaberController : Controller
    {
        public string GenerateSlug(string phrase)
        {
            string str = phrase.ToLower();
            // invalid chars           
            str = Regex.Replace(str, @"[^a-z0-9\s-]", "");
            // convert multiple spaces into one space   
            str = Regex.Replace(str, @"\s+", " ").Trim();
            // cut and trim 
            str = str.Substring(0, str.Length <= 45 ? str.Length : 45).Trim();
            str = Regex.Replace(str, @"\s", "-"); // hyphens   
            return str;
        }

        private readonly IHaberService haberService;
        public HaberController(IHaberService haberService)
        {
            this.haberService = haberService;
        }


        // GET: Admin/Haber
        public ActionResult Index()
        {

            var haberler = haberService.GetAll();

            return View(haberler);

        }

        public ActionResult Create()
        {
            var Haber = new Haberler();
            
            return View(Haber);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Haberler Haber,HttpPostedFileBase upload)
        {
        
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(upload.FileName);
                    string extension = Path.GetExtension(fileName).ToLower();
                    if (extension == ".jpg" || extension == ".jpeg" || extension == ".png" || extension == ".gif")
                    {
                        var photoname = Haber.HaberBaslik;
                        fileName = photoname + extension;
                        string path = Path.Combine(ConfigurationManager.AppSettings["uploadPath"], fileName);
                        upload.SaveAs(path);
                        Haber.HaberPhoto= fileName;
                        Haber.Slug = GenerateSlug(Haber.HaberBaslik);
                        haberService.Insert(Haber);
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ModelState.AddModelError("Photo", "Dosya uzantısı .jpg, .jpeg, .png ya da .gif olmalıdır.");
                    }
                }
                else
                {
                    haberService.Insert(Haber);
                    return RedirectToAction("index");
                }

            }
            
            return View(Haber);

        }
        public ActionResult Edit(Guid id)
        {
            var haber = haberService.Find(id);
            if (haber == null)
            {
                return HttpNotFound();

            }
            return View(haber);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Haberler haber, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                var model = haberService.Find(haber.Id);
                if (upload != null && upload.ContentLength > 0)
                {
                    
                    string fileName = Path.GetFileName(upload.FileName);
                    string extension = Path.GetExtension(fileName).ToLower();
                    if (extension == ".jpg" || extension == ".jpeg" || extension == ".png" || extension == ".gif")
                    {
                        string path = Path.Combine(ConfigurationManager.AppSettings["uploadPath"], fileName);
                        upload.SaveAs(path);
                        haber.HaberPhoto = fileName;
                        haberService.Update(haber);
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ModelState.AddModelError("Photo", "Dosya uzantısı .jpg, .jpeg, .png ya da .gif olmalıdır.");

                    }
                }
                else
                {
                    // resim seçilip yüklenmese bile diğer bilgileri güncelle
                    haberService.Update(haber);
                    return RedirectToAction("index");
                }            
            }

            return View(haber);
        }
        public ActionResult Delete(Guid id)
        {
            haberService.Delete(id);
            return RedirectToAction("index");

        }

        public ActionResult Details(string Slug)
        {
            var haber = haberService.Find(Slug);
            if (haber == null)
            {
                return HttpNotFound();

            }

            return View(haber);
        }



    }
}

Haber.Web/Areas/Admin/Views/Haber/Create.cshtml
@model Haber.Model.Haberler

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm("Create", "Haber", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Haberler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HaberBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberDetay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.HaberDetay, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HaberDetay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.HiddenFor(model => model.HaberPhoto)
            @if (!string.IsNullOrEmpty(Model.HaberPhoto))
                {
                <img src="@Model.HaberPhoto" style="width:300px;" /><br />
            }
            <input type="file" name="upload" />
            @Html.ValidationMessageFor(model => model.HaberPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberSirano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberSirano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberSirano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">

                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    <span>Aktif Olsun</span>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
    
}

<div>
    @Html.ActionLink("Ana Sayfa", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Haber.Web/Areas/Admin/Views/Haber/Delete.cshtml
@model Haber.Model.Haberler

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Haberler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HaberBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HaberDetay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberDetay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HaberPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HaberSirano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberSirano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Haber.Web/Areas/Admin/Views/Haber/Details.cshtml
@model Haber.Model.Haberler

@{
    ViewBag.Title = "Detay";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Haberler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HaberBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HaberDetay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberDetay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HaberPhoto)
        </dt>

        <dd>
            <img src="~/CmsFiles/@Model.HaberPhoto" style="width:30px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HaberSirano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HaberSirano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Haber.Web/Areas/Admin/Views/Haber/Edit.cshtml
@model Haber.Model.Haberler

@{
    ViewBag.Title = "Düzenle";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Haber", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Haberler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HaberBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberDetay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.HaberDetay, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HaberDetay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.HaberPhoto)
                @if (!string.IsNullOrEmpty(Model.HaberPhoto))
                {
                    <img src="~/CmsFiles/@Model.HaberPhoto" style="width:100px;" /><br />
                }
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.HaberPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HaberSirano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HaberSirano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HaberSirano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Düzenle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @*@Html.ActionLink("Detay", "Details", new { id = Model.Id })*@,
        <a href="/haber/@Model.Slug">Detaylar</a>
    </div>
<div>
    @Html.ActionLink("Ana Sayfaya Geri Dön", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Haber.Web/Areas/Admin/Views/Haber/Index.cshtml
@model IEnumerable<Haber.Model.Haberler>

<h2>Haberler</h2>

<p>
    @Html.ActionLink("Haber Oluştur", "Create")
</p>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="deleteModalLabel">Uyarı</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bu haberi silmek istediğinize emin misiniz?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Hayır</button>
                <a href="" id="modalYes" class="btn btn-danger">Evet</a>
            </div>
        </div>
    </div>
</div>

<section class="panel">
    <div class="panel-body">
        <table class="table table-bordered table-striped mb-none" id="datatable-default">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.HaberBaslik)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HaberPhoto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HaberSirano)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsActive)
                        
                    </th>
                    <th>
                        
                        @Html.DisplayNameFor(model => model.UpdatedAt)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="gradeX">
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.Id })">@Html.DisplayFor(modelItem => item.HaberBaslik)</a>
                        </td>
                        <td>
                            <img src="~/CmsFiles/@item.HaberPhoto" style="width:30px" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HaberSirano)
                        </td>
                        <td>
                            @{
                                if (item.IsActive == true)
                                {
                                    <label for="success" class="btn btn-success">@item.IsActive</label>
                                                               
                                }
                                else
                                {
                                    <label for="success" class="btn btn-danger">@item.IsActive</label>
                                }
                            }

                        </td>
                        <td>
                            
                            @Html.DisplayFor(modelItem => item.UpdatedAt)
                        </td>
                        <td>     
                            <div class="delete-section">
                                @*<a class="delete-link"  href="@Url.Action("Delete", new {id = item.Id})"></a>*@
                                
                                @*<div class="btn btn-primary delete-confirm" style="display:none" data-delete-id="@item.Id"></div>*@
                                <label class="btn btn-danger">
                                    <p> @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { onclick = "return confirm ('Silmek istediğinize emin misiniz')" })</p>
                                </label>
                            </div>
                           @*<a href="@Url.Action("Delete", new { id = item.Id })">Sil</a>*@
                           
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

<style>
    .delete-section {
        display: inline;
    }
    .badgebox {
        opacity: 0;
    }

        .badgebox + .badge {
            /* Move the check mark away when unchecked */
            text-indent: -999999px;
            /* Makes the badge's width stay the same checked and unchecked */
            width: 27px;
        }

        .badgebox:focus + .badge {
            /* Set something to make the badge looks focused */
            /* This really depends on the application, in my case it was: */
            /* Adding a light border */
            box-shadow: inset 0px 0px 5px;
            /* Taking the difference out of the padding */
        }

        .badgebox:checked + .badge {
            /* Move the check mark back when checked */
            text-indent: 0;
        }
</style>
@section scripts{


    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable-default').dataTable({
                "language": {
                    "lengthMenu": '<select>' +'<option value="2">2</option>'+ '</select>'
                },
                "bDestroy": true
            });
        });
      //  			    $(document).ready(function () {
      //                      $('#datatable-default').dataTable({
      //                 "language": {
			   //       "lengthMenu": 'Display <select>'+
			   //         '<option value="10">10</option>' +
		    //        '<option value="20">20</option>' +
			   //         '<option value="30">30</option>' +
			   //       '<option value="40">40</option>' +
			   //          '<option value="-1">All</option>' +
			   //           }
      //            } );
			   //} );







    $(function () {
        $("a.delete-link").click(function () {

                var deleteLink = $(this);
                deleteLink.hide();
                var confirmButton = deleteLink.siblings(".delete-confirm");
                confirmButton.show();
                

                var cancelDelete = function () {
                    removeEvents();
                    showDeleteLink();
                };
            
            var deleteItem = function () {
                removeEvents();
                confirmButton.hide();
                $.post(
                    '@Url.Action("Delete")',
                    AddAntiForgeryToken({ id: confirmButton.attr('data-delete-id') }))
                   .done(function () {
                       var parentRow = deleteLink.parents("tr:first");
                       parentRow.fadeOut('fast', function () {
                           parentRow.remove();
                       });
                   }).fail(function (data) {
                       alert("error");
                   });
                return false;
            };

            var removeEvents = function () {
                confirmButton.off("click", deleteItem);
                $(document).on("click", cancelDelete);
                $(document).off("keypress", onKeyPress);
            };

            var showDeleteLink = function () {
                confirmButton.hide();
                deleteLink.show();
            };

            var onKeyPress = function (e) {
                //Cancel if escape key pressed
                if (e.which == 27) {
                    cancelDelete();
                }
            };

            confirmButton.on("click", deleteItem);
            $(document).on("click", cancelDelete);
            $(document).on("keypress", onKeyPress);

            return false;
        });

        AddAntiForgeryToken = function (data) {
            data.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
            return data;
        };
    });
    </script>
    }